apiVersion: v1
kind: Secret
metadata:
    name: aws-credentials
type: Opaque
stringData:
    credentials: ENC[AES256_GCM,data:6Zjz5fjRx+gfzU0Bxs2fzuGgLoArtyJJI5ayGOU/cUclP7jKEFJvKPau6wpjTRlbBavYHBMJtBXLptw5QEoHOYS31UlUiGcLEf2p9vr+IZpSTvPkuPupX3S39vr1MJF4ujB82oY6PabZQNZ1fgivtYgLKl0hluCVpGe3GBgUuEFMIEf4Y/lXhhB70WuVxJcRm69Cp0jXzQKlPY1f/2fCvuDU8V4I4F9SOnzLZl96XHEZVr4Uy7m8F45IrgWduX1+xjljegzstbO9IqUFpLkuZG4lwV2WbRP4p+vNUXitUbCHZKBoyES5a1GIAC+CqPPhLOX9mKj84GUp6Gm9bZ/eaeV5tlOhA74kn1OEuWE39zGaDvDLbBeKWj6gmZ9zFDrewGADg//nQr6oMtOG4qT1MNj+m0M2JIAQsmjCXpy/d2WT4c+3gXOu7acyZ81G3OfgI59AAKwhOGU4n94nstCsZgv/evyq4r8/em7aINqB5ZdUtF5yuiYQPRIVe/aWh0zNWiK+AtxhrzDDHzLjWQ5S/8ZRX7YfmIuVtr0JhTZvlKcbNSI6LBVW0+71yELlmHsrzXyKhO7nP25Qec85cLdOrYew+Hi5+jnL0N7nyPLl2IveDmZPCcSswB+c3CzRyb2ZvPPqSGBZ+HxCfLAnw3kDvRIwBDkZ0E+qUrvgcOSITgilx3CgMEAp+16jWlYVR04HIr654opjLjhFZdc+BRjN0zi5+/Li//VlFNHY+G+qrDkXZaNs59QZhP3UmFI43iJchyMGJ2gIbAHRuzDMBc4VEtip/+YV5f1jUgYavmlTjuKGGqQoUnAd4kKsHELWuppwAmn6CuzJcIgv9QuIkOWL2Ef0Xjr0OX3NnjxtdeONba8lDmp3LoxLnUXd6awTiifK3rcK8wFcr0JVX7DxqxmlVQ/ZZQdIYOMj9ya/BwcpWfQfFz2QaseKCeNhSumUkF9AEvUxKL8IrFsNDVVGlfRwliWfTB/Oq91CDXIS+LFKLDDzQBavBlNa3KrWFcBAb5xgoUU/z76zG4OQK0QfIxOw5i4yEe63BAEnbEpuVH/vwUjGl4/xGlcNncp1B5gjci4D9OjARvQw2Y3oieVTH72bmo49lwnXI8qJ8XA0bku1K7qjYG7EkMfRCV4PSn+7SCdKWsFy9b4v8CvKhh1O9Ortk7uSSfT1vh+QpXb3/RVQIc/YA9/WMgL3BD9GZqm04SZoIsNQ8pU7NisAhIvGfXChB7CgWAu0ZZgI9x6/ierXmFOSbY9mEMxL9L3lS/CqQyO7CKzQJbdi/GfbJnqBaAN2MisTngJD1d2VtVqRf9YX8P79jOfzHuGFTkndjsnDbZsp4kDqzshAPFQH,iv:aVnTGb0zqARczaDXcLfKaNer8TX5iJD+EdURwcG1Rok=,tag:LjPUmk/koMbiOZVaBCvzOg==,type:str]
    config: ENC[AES256_GCM,data:Gy4a3COvhOcxML8RFGluvXKSIDcP1k89zDTMF67EY6lPrtejh7iludmzcg==,iv:YaKrsndk2uqQEJPAuGHPn0Vh0ktHtG+v/3t/5EZDkUU=,tag:kR1dsQiWyTSn8r0NsDgHDQ==,type:str]
sops:
    age:
        - recipient: age1h7l5m2x3j86v0crvfq7s5rj7sx2ckn0xpewc6yymwtv98v3cz3hsz4jrfa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByajFCeXA4MjhSd2srSWJm
            djMzd3FCWVpqbXBTNW9TeUxsQzh6bGpRMkNVClhpdUE4N2xaWjhUNi9QSTF6TVpl
            Qm03MThKcHdrSk5zOThUbjdYWUZ6MzAKLS0tIHNZYmk5RG44czVtd2ZZa0MzN2FB
            dDdOdUd0YkMxRGdyK0YyOWRBRG9laDgKQOMCrzR14MERFHNyU8SoDXInUuQ+RAUj
            LemrUw9I+yKI4YNI6EuEJ52O6+YJtTd45o/RL5r+sCQz1ykf/ZtuuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-04T17:52:25Z"
    mac: ENC[AES256_GCM,data:/g09emApU7F0BTadHLAA09ZPEmmWUqBN5VnRQtzezCn/fSRK4J6nFYnHf5TqN26WPIdkJD7lMRsoEbV6MaxiKog90XUP3yegVskibB7si/pN/u7eh0sUvfbbKbkdlCOQnnx3cSWDuo0pzL7GCdqARvbS1LTdnpM8K/7ELQ4RZbo=,iv:JhqvmzBorWZ2AnygoCfI7TR4QX+5Erg0y9sYA8ixjN4=,tag:EbMPVC4nadYYkt1BaPQ8UQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.0
