apiVersion: v1
kind: Secret
metadata:
    name: aws-credentials
type: Opaque
stringData:
    credentials: ENC[AES256_GCM,data:vXSM3Vav3YhC0YMQH1gi2Dg0zXtyu+sH3XxrAazb6MJTABsP2G7RXSQ8jM9TxrPCjBV5z6V1rac1/CLJ+UhOUXvsTI62X/h4IFeOszVq3Jt19Vur+t5aV+i8s978bLKH738dYk7KfJRuhjg9T+Bzd8LUicgesM9vmrAHcF+0inJNG8AGGWUaDg6opeSD6TCTOrIkLRWN6IJRuXn8qO8Dt1iCNVfzwS3R0NqRQ46SzbSfc4vH2SPHcJBHzXmXeVCXMibKgZfr14uY2kIsuoTbyn7DYOngQRikoOzlSauE+AOxvqvwSG+P6YgYxMTipUO3srqSfGpKSzcY40dneaY7M+q5D89kjnLw2IAGGtsCZ4B7BEetnzTS5zpzneF4yuSdLT6Unz3+iCboJBxP2J1tVzF4AxDGi2IVzK4Ld0peDt0NWigIgHmWYi3mwxdzNA0VlKjQ+CWgnT+T50pVYDEoh1gT8zxiU0BnHC74UVmq1g8lAUSaHkwaIFZlKGBL3ZEKUIJ21++mDM12fhE73MoDeQusN/BbN0ODaLmNvNmFtV1SC4Xa8wwBDrg/tzy8SRXlftz8eM9RNB2HwBuMCYBS8CcxgboSg6Y4rAa1FG6J16GzLUX5TdWF0tSbNTZMhSYD13S4pxGhxR9LN+1/cjvtapu7R5QtL+8jpSbmrEb1mFdDE6FSXtH1aX4C8dkrGSyqsMsR808X2DGsljFcHTeENiSO/8mTJur5jgohLpV3RDoW0IOXCN6eYKzAErZa5ybqZ5RNaIzGuN8UEbD/FkpFHljk6XQApnhcEDRKJaTVxEaOgm+PbqDydZbnKqTTBij0KuPvYTSrt58x9/nf60V78N28TxKj1ag628x5D5mOPLm0BVzCsWL89p0nBlS2pjFVnoOFn5eOjndsZEhEsJghk5i+uElTTGgjZvYqFHD6nYf8nm6H1JWNPE3P5WJgMTOtbdE6oHrqh4mHebA8te3UaCDKnENUFb/FES22k1uhKl4+ZxYyoGuQO1XljzjaS1bbZVZmpJNgF2ljcFQXnEIyS4sn0X3hpU5tR5XMegTPZr0Cqt+AvFYbVR/7WabshCodISRn5AQNo69wwusXjDWCwPpZQJ6B2B8Vue3xi9+7qW45OgiHsnqXexylkCUKFU0vuRguNagzvqOakem9zz9pdX9OTrPxGqIMTaWyf+WoYQNuqwPn7/qsWnAE5UyNZ9V8240+Z1OyOL+j9gFmwoQqntztn88s36iRVCRxxLMh0b8S77Icf0qSivaRshX6/mvlCOjnIJnz01GQ4GloFVnrxq7C1ufdX5ZT0viHU1KoafxWqL+/8TfEVgr6Pvl0j4PVRfXzfaa67q0j,iv:T+bpIFLD5qnSMekCdvSD+Jb9EmK4Ga9+sSMAteGjurA=,tag:pZM+w/Shgdr5briahEe6eQ==,type:str]
    config: ENC[AES256_GCM,data:dQjpuaHkZ4xBdRzZGTAFxv4dJGQcaWo/G/30wHRWKckEan0JUjHBjq0ipg==,iv:riogMyYuiBQuIwKBoj8EWrwewrOQe5LaVM9SIxYx670=,tag:5Hnn9zY+k21HU/aHykgveA==,type:str]
sops:
    age:
        - recipient: age1h7l5m2x3j86v0crvfq7s5rj7sx2ckn0xpewc6yymwtv98v3cz3hsz4jrfa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLNjVJTkVDRVJmQlFuLzVt
            bjRQZFBiaFVLUWZHZE9yVENIZmNPVytiVm5jCjZyNmUxaTNJMm1mOFJkYnI4Z0Fn
            Z2MyNEdSbEVrc3d0QVJIc0NtSDhIK28KLS0tIGNueXpYTldac2xjK3F5aE4wMkpi
            TExrOVhweWsrRDl4M2FaUVAxRGJ4RVEKxNdQBoXA2H8SEefcMgL5ilK2xTC2yCTg
            umHtRBkTNF3i025LIBH+X5j2lFByxVbxlevPX6Nctmc+ARd26ncH5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-04T16:58:09Z"
    mac: ENC[AES256_GCM,data:mDphcurbY9nbLWmP+GenZs3JDBQn1RQQIDUjqj6IjXs42lBC2zVvSRmwo5qwgszs3OclcSPWN85eSOhclhL5X6p0yL5K8L+EByGLtFbXWye0zZzLs4EXfPg9H+vt/oblD3xOWOYFW7/NeWCgUP+w0GGak1t4qPHAK5r3YqTGnEM=,iv:DC1Yz+lF8r07kOVxflnVGQcfkwAF59qSR8DhFv64QW0=,tag:BT1FotbtewJDB7So/+46ng==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.0
