apiVersion: v1
kind: Secret
metadata:
    name: aws-credentials
type: Opaque
stringData:
    credentials: ENC[AES256_GCM,data:R0SFkxOvRmTgRIbOacUnwr0cwpxoPHkPMnthlshNx749cO7nT1fB6zdU4MNX5VPb/cEYZbC4Q8N4ycLX8TI6dg4g2fEQNSCSdWuy6uzn4YIm2yjZ+YUBFzm+HtaYGl3JZJFnktMD6f4ueqNB4IwHLJdbLPoC0w54pNM1xGXqgNfwS7SjGE7xGTIigXWsV+4e0nh/izCO90FEZkKlqdTsFUjPgDDKR5c6mRqPMh92bh7Jmkhq0E82vGyCKFwBFgwcXoVqUtzaNcUWho1DzaupaVprWcmS2gZMSEwQdo39rh06IaievuV4+OtZE28XqvIsMa9wvPkwdqeMhFScxPts08YAwILm8vxIf+cwOR6InaQcvddWKOUTL8r6Mae93F8bCJG4NLv3MKufaus76dmZos9cX2wdvp0HbmTEdwDDcIB2Yr46ZMSyS+Whc+3n1emci/r0IxHWGlSczu9VtCs8uAruqQDmSsNozSNTX6LUY41rgVPrxUBWKnw0LnAyCotdgJ9iHT/ioHKdOUphEsl2X58qfLrtDud0cOgCU+VZ2NPiiAkYEOIjsaODDYmYxWjg01yHoiEpYhZVK2AznkIIXGae5H0b9YHlWgGeEVFPu5iLFGr9iAiWCoLj6ht3OCSIwm1p215jzM9z2eOQllNkRXoFWc5PV1zX/DIvUaK2uyubdLia4qb9ewdfiaGPRRFW+3Yf3v+n/MF/y0wAppctwF7VHmobWVnZbhlSX2EsXg51l6zJ8aJzpY6r/XzS5HRnZfyK+HSGOnUoNpcARfSPnG+oP0AEGZbwJ9sel9hw9RdMfT6Giv6oLNi7ZxeJlV8BBgtKpTaUmSLE1ziZuFC5SDJaZaNGG2GEmmZccNXDbpZua4Dt4yl8es65PeSmeVE1i8swNavmFMDIm/Pbo4HWG8PjNgf+IxhVCcUHW8G5hurlzS4CuXh7Y6gazW3Wbgj9SmPu4M8tXCcKc/R6+8E6Sz6V3iARLXa4bR779kJmp55Z19FNFWMeoT4i9PX2d93XP/NSr7GqNsdLvdl0GlQG1CVy4Kki6APWnw2AmhXBg4WvSr0gjswclKC7uKuM3Ejyw/IEghMDAZcMAVJfqjQSg1ceMgJgZkBTdczxVaIB/DTA8ZuMFtttNH2Saj/qS5myTESr6+AJGlWeKbES/88i+FFpGC4+eEnj3Wzxwg7Eedzg5vqzye+E4NxOMXqAGS4NB5nRD1y70/hlNhGGNCqyhhKs2IX54aLqOB2A4JAnAWwnyqze5aOPqKT76NWxIbOnNbVGiOj4FUeLdsC9tPhrh1zMKyG3F9hTPzmCwFn3FvulgVgfwDBdQqlv+Q0ehuyYJVl7CR6PHcNK,iv:Du24wYfLVzNaciD4hg91PN0U5jPVuUH85ZM6bswAFRI=,tag:7UW3JDgTBg8ZWh2B/kwB/w==,type:str]
    config: ENC[AES256_GCM,data:E1OicgZ1JLsm6X7xhFZlABs2UNT7cISmGuqnckp3uLI9/Qb65u1kiO9nSA==,iv:q3PcPoxSwatx0D7cNui5JDY7+FYNzqAGG88wHKV9jvQ=,tag:L9XUTNdGFz5qnsRS75zfww==,type:str]
sops:
    age:
        - recipient: age1h7l5m2x3j86v0crvfq7s5rj7sx2ckn0xpewc6yymwtv98v3cz3hsz4jrfa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4TEd5UU12V0w5MllZWE51
            azFndERqOWhqb2NwL2d0cCtVSUdobU9QVWp3ClFQMlpUcUxYcWVqZ0JGTWpsM1Vk
            L2M3ZnpjWWR4MzUzWGFBUEVxaE1LVDAKLS0tIE1SRmNKQ0hRaGU0SGg4MEgyKy9C
            cDA1OXhZdzlvNkRJais1UVg5ems2c1EKgUKY+D2JgNs2bvOeyyDIcQ7IRSkrHH2N
            Q+7xi/SHTWYIzrxDHku8Bk/VkejlDB0pd20D9KPJb/omGr1DJTdmiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-04T21:39:45Z"
    mac: ENC[AES256_GCM,data:ljiGCgwTSyuv9RniL9qEcXh9tapHqQDaby1dTmrNNg81/1a6pT9e1W49cZsD0P1eU5wXkMbE3LuJdQivhzP/9LZ2eBmxCd8TYsVIiBLtWR/U0hmJEiiBAeQUndy4kzatsU7rl1rn78Z6IKK/NbBys9m5MIrFwQkH2YkDAYPv+wY=,iv:xRWT+rMk71voxMNibxgURIkZA5AwtiKBflkkQCjaq5U=,tag:6TocMNgkYp70//KMWeKz0g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.0
