apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: data
resources:
  - ../../base
patches:
  - path: deployment-patch.yaml
  - path: cronjob-patch.yaml
images:
  - name: producer-api
    newName: producer-api
    newTag: localdev-1772326913
