apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-api
spec:
  template:
    spec:
      containers:
        - name: producer-api
          imagePullPolicy: Never
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "data-lake-kafka-kafka-bootstrap.strimzi.svc.cluster.local:9092"
            - name: POSTGRES_DSN
              value: "postgresql://postgres:postgres@sample-postgres.data.svc.cluster.local:5432/trading"
            - name: SIMULATION_ENABLED
              value: "true"
            - name: SIMULATION_INTERVAL_SECONDS
              value: "5"
