apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - cronjob.yaml
  - cronjob-nonmnpi.yaml
configMapGenerator:
  - name: producer-api-seed-data
    files:
      - seed-data.json
