apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: strimzi-connect
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - cluster: localdev
          # - cluster: prod  # Uncomment when deploying to a real EKS cluster
  template:
    metadata:
      name: 'strimzi-connect-{{ .cluster }}'
    spec:
      project: default
      source:
        repoURL: file:///mnt/data-lake-platform
        targetRevision: HEAD
        path: 'dev/gitops/strimzi/overlays/{{ .cluster }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: strimzi
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - SkipDryRunOnMissingResource=true
          - ServerSideApply=true
        retry:
          limit: 10
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 5m
