apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: data-lake-connect
  annotations:
    strimzi.io/use-connector-resources: "true"
    argocd.argoproj.io/sync-wave: "1"
spec:
  version: 3.6.0
  replicas: 1
  bootstrapServers: data-lake-kafka-bootstrap:9092
  config:
    group.id: data-lake-connect
    offset.storage.topic: connect-offsets
    config.storage.topic: connect-configs
    status.storage.topic: connect-status
    offset.storage.replication.factor: 1
    config.storage.replication.factor: 1
    status.storage.replication.factor: 1
    key.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter: org.apache.kafka.connect.json.JsonConverter
    key.converter.schemas.enable: false
    value.converter.schemas.enable: false
  build:
    output:
      type: docker
      image: localhost/data-lake-connect:latest
      pushSecret: ""
    plugins:
      - name: debezium-postgres
        artifacts:
          - type: tgz
            url: https://repo1.maven.org/maven2/io/debezium/debezium-connector-postgres/2.5.0.Final/debezium-connector-postgres-2.5.0.Final-plugin.tar.gz
      - name: iceberg-sink
        artifacts:
          - type: maven
            group: io.tabular
            artifact: iceberg-kafka-connect-runtime
            version: 0.6.19
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi
