apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: iceberg-sink-mnpi
spec:
  config:
    iceberg.catalog.type: "hadoop"
    iceberg.catalog.warehouse: "s3a://datalake-local-iceberg-dev/mnpi"
    iceberg.catalog.io-impl: "org.apache.iceberg.aws.s3.S3FileIO"
    iceberg.tables: "default.mnpi_events"
